name: fromtend

'on': push

jobs:
  frontend:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: buuld
      run: make build

    - name: docker-build
      run: make docker-build

    

